# Generated by Django 3.1.7 on 2021-03-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailor',
            name='div',
            field=models.CharField(blank=True, choices=[('31', '31'), ('31A', '31A'), ('31B', '31B'), ('31C', '31C'), ('31D', '31D'), ('31E', '31E'), ('32', '32'), ('32A', '32A'), ('32B', '32B'), ('32C', '32C'), ('32D', '32D'), ('32E', '32E'), ('33', '33'), ('33A', '33A'), ('33B', '33B'), ('33C', '33C'), ('33D', '33D'), ('33E', '33E'), ('34', '34'), ('34A', '34A'), ('34B', '34B'), ('34C', '34C'), ('34D', '34D'), ('34E', '34E'), ('35', '35'), ('35A', '35A'), ('35B', '35B'), ('35C', '35C'), ('35D', '35D'), ('35E', '35E')], max_length=3, null=True, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='sailor',
            name='dept',
            field=models.CharField(blank=True, choices=[('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35')], default='35', max_length=2, null=True, verbose_name='Department'),
        ),
    ]
