# Generated by Django 3.1.7 on 2021-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0002_auto_20210318_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sailor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='sailor',
            name='div',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='Division'),
        ),
    ]
