# Generated by Django 3.1.7 on 2021-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0003_auto_20210511_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailor',
            name='coversheet',
            field=models.BooleanField(default=True, verbose_name='Cover Sheet Uploaded'),
        ),
    ]
