# Generated by Django 3.1.7 on 2021-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0004_sailor_coversheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailor',
            name='coversheet',
            field=models.BooleanField(default=False, verbose_name='Cover Sheet Uploaded'),
        ),
    ]
