# Generated by Django 3.1.7 on 2021-05-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0005_auto_20210511_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sailor',
            old_name='in_teams',
            new_name='teams_type',
        ),
    ]
