# Generated by Django 3.1.7 on 2021-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0006_auto_20210518_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailor',
            name='in_teams',
            field=models.BooleanField(default=False, verbose_name='In Teams'),
        ),
    ]
