# Generated by Django 3.1.7 on 2021-05-27 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0008_unavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailability',
            name='end_dt',
        ),
        migrations.RemoveField(
            model_name='unavailability',
            name='start_dt',
        ),
        migrations.AddField(
            model_name='unavailability',
            name='end',
            field=models.DateField(default=datetime.date(2021, 5, 27), help_text='End Day/Time', verbose_name='End of Unavailability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unavailability',
            name='start',
            field=models.DateField(default=datetime.date(2021, 5, 27), help_text='Start Day', verbose_name='Beginning of Unavailability'),
            preserve_default=False,
        ),
    ]
