# Generated by Django 3.1.7 on 2021-06-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0008_unavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ua',
            name='end_dt',
        ),
        migrations.RemoveField(
            model_name='ua',
            name='start_dt',
        ),
        migrations.AddField(
            model_name='ua',
            name='end',
            field=models.DateField(help_text='End Day/Time', null=True, verbose_name='End of Unavailability'),
        ),
        migrations.AddField(
            model_name='ua',
            name='start',
            field=models.DateField(help_text='Start Day', null=True, verbose_name='Beginning of Unavailability'),
        ),
    ]
