# Generated by Django 3.1.7 on 2021-05-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0009_auto_20210527_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unavailability',
            new_name='UA',
        ),
    ]
