# Generated by Django 3.1.7 on 2021-06-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0009_auto_20210605_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailor',
            name='in_slack',
            field=models.BooleanField(default=False, verbose_name='In Slack'),
        ),
    ]
