# Generated by Django 3.1.7 on 2021-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0010_sailor_in_slack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sailor',
            name='in_slack',
        ),
        migrations.AddField(
            model_name='sailor',
            name='slack_act',
            field=models.BooleanField(default=False, verbose_name='Active Slack'),
        ),
        migrations.AddField(
            model_name='sailor',
            name='slack_inv',
            field=models.BooleanField(default=False, verbose_name='Slack Invite'),
        ),
    ]
