# Generated by Django 3.1.7 on 2021-07-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0011_auto_20210616_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailor',
            name='slack_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Username'),
        ),
    ]
