# Generated by Django 3.1.7 on 2021-07-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0012_sailor_slack_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sailor',
            name='slack_act',
        ),
        migrations.AddField(
            model_name='sailor',
            name='in_slack',
            field=models.BooleanField(default=False, verbose_name='In Slack'),
        ),
    ]
