# Generated by Django 3.1.7 on 2021-07-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0013_auto_20210709_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sailor',
            name='slack_inv',
        ),
    ]
